### PR TITLE
Sapdev sf refactor

### PR DESCRIPTION
**Pull request by sfarrens**
## Summary

- Replaces PR #8 
- Cleaned up CMake style and structure
- Added build instructions for macOS
- Removed Travis-CI
- Added PyQT to pre-install requirements

## Notes

- `IM_VisTool.h` and `IM_VisTool.cc` moved from `src/cxx/mr` to `src/cxx/misc`

### CODE REVIEW

**Comment by sfarrens** [comment]
Hi @jstarck, this is working perfectly on my laptop. There still appears to be an issue when I test this on the GitHub CI, so there may be a missing dependency somewhere.

Please test this branch on your machine and let me know if everything works.

To install the requirements I recommend you run:
```bash
brew tap sfarrens/sf
brew install armadillo bigmac cfitsio cmake fftw gsl healpix libomp
```

If you already have all/some of these packages installed be sure to run:
```bash
brew update
brew upgrade
```
to ensure everything is up to date.

Finally, you can checkout this branch to test as follows:
```bash
git fetch origin pull/9/head:sam_branch
git checkout sam_branch
```

Then to build I suggest you run:
```bash
python setup.py install
```

To avoid any issues, I recommend you build this package in a clean environment. _e.g._:
```bash
conda create -n test_pycs python=3.9 pip -y
conda activate test_pycs
```

**Comment by sfarrens** [comment]
@jstarck You can see the latest build of the pycs package [here](https://github.com/CosmoStat/cosmostat/runs/4765464388?check_suite_focus=true). This was run on macOS 10.15.7 in a Python 3.9.7 Conda environment. You can see the result of running `python setup.py test` under the `Run Tests` section and you can also check the dependencies installed using Homebrew under the `Install macOS Dependencies` section.

**Comment by jstarck** [comment]
The compilation works well, c++ binaries are all there and running properly.

**Comment by jstarck** [comment]
The compilation works well, c++ binaries are all there and running properly.

**Review by jstarck — APPROVED** [review]
Compilation on  mac OS 11.5.1 ok, c++ binaries running ok as well

**Pull request merged**
